spring:
  application:
    name: movie-info-service

  data:
    mongodb:
      username: ${MONGO_DATABASE_USER}
      password: ${MONGO_DATABASE_PASSWORD}
      database: ${MONGO_DATABASE_NAME}

  sleuth:
    sampler:
      percentage: 1.0

# Server
server:
  port: 8080

# Management
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Logging
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
          %clr([${spring.zipkin.service.name:${spring.application.name:-}},){magenta}%clr(%X{X-B3-TraceId:-},){yellow}%clr(%X{X-B3-SpanId:-},){cyan}%clr(,%X{X-Span-Export:-}]){blue}%clr([%8.15t]){cyan}
          %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
