apiVersion: skaffold/v2alpha3
kind: Config
profiles:
  - name: monkey
    activation:
      - kubeContext: dev/console-c3smonkey-ch:8443/developer
    build:
      insecureRegistries:
        - registry.apps.c3smonkey.ch
      tagPolicy:
        sha256: {}
      artifacts:
        - image: registry.apps.c3smonkey.ch/dev/catalog-service
          jib:
            args: ['-Dimage=registry.apps.c3smonkey.ch/dev/catalog-service']

        - image: registry.apps.c3smonkey.ch/dev/customer-service
          jib:
            args: ['-Dimage=registry.apps.c3smonkey.ch/dev/customer-service']

        - image: registry.apps.c3smonkey.ch/dev/order-service
          jib:
            args: ['-Dimage=registry.apps.c3smonkey.ch/dev/order-service']

        - image: registry.apps.c3smonkey.ch/dev/gateway-service
          jib:
            args: ['-Dimage=registry.apps.c3smonkey.ch/dev/gateway-service']
    deploy:
      kustomize:
        paths: ["catalog-service/k8s/overlays/dev",
                "customer-service/k8s/overlays/dev",
                "order-service/k8s/overlays/dev",
                "gateway-service/k8s/overlays/dev"]

  - name: local
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: catalog-service
          context: catalog-service
          jib: {}

        - image: customer-service
          context: customer-service
          jib: {}

        - image: order-service
          context: order-service
          jib: {}
        - image: gateway-service
          context: gateway-service
          jib: {}
      local:
        push: false

