apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "movie-catalog-pipeline", "namespace": "", "kind": "DeploymentConfig"}]'
    name: movie-catalog-pipeline
  spec:
    source:
      git:
        ref: movie-catalog-service
        uri: https://github.com/marzelwidmer/microservices-demo.git#master
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic